name: tatweerui
description: "A UI library for Flutter providing custom buttons, switches, dialogs, and more."
version: 0.0.10
homepage: https://tatweerresearch.org
repository: https://github.com/mohammednAlogly/tatweerui-flutter


environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


fileName: src/tatweerui.dart  

flutter:
  
  plugin:
    platforms:
      ios:
        pluginClass: TatweeruiPlugin
        sharedDarwinSource: true
      android:
        package: com.tatweer.ui
        pluginClass: HelloPlugin  
      linux:
        pluginClass: TatweeruiPlugin
      macos:
        pluginClass: TatweeruiPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: TatweeruiPlugin
      web:
        pluginClass: TatweeruiPlugin

      


  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
